source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               lib/gson-2.10.1.jar,\
               lib/plantuml.jar,\
               plugin.xml,\
               LICENSE,\
               README.md,\
               about.html,\
               icons/
src.includes = src/,\
               lib/,\
               META-INF/,\
               plugin.xml,\
               build.properties

